### ISSUE TITLE
Linear Regression 'Data' Diverging

### ISSUE THREAD

**Issue by guner-aygin** [guner-aygin/Year-4-Project#1]
On the Linear Regression notebook, in the first block of code where I create the data I've noticed that when I make x large the y values seem to diverge away from the true values. 

How do I rectify this? Or is this supposed to happen?

**Comment by grd349** [comment]
```
y = m_true * x + b_true # --> 'true' y value
y += np.abs(f_true * y) * np.random.randn(N) # --> adds N normally distributed random values
y += yerr * np.random.randn(N)
```

The middle line here, what is it supposed to be doing? 

I would write this either, 

`y = m_true * x + b_true + yerr * np.random.randn(N)`

or even 

`y = np.random.normal(loc=m_true * x + b_true, scale=yerr, size=N)`

Make any sense?

**Comment by guner-aygin** [comment]
The middle line is supposed to be making the data noisier, rather than just having large errors. I've managed the achieve the same result by just multiplying the scale by our f_true value.

`y = np.random.normal(loc=m_true * x + b_true, scale=yerr*f_true, size=N)`

Thanks.

**Comment by grd349** [comment]
> Or is this supposed to happen?

It's up to you, but I would say it would be easier to deal with conceptually if it does not but either way!

**Comment by guner-aygin** [comment]
The good thing about having the small amount of divergence is that it 'messes up' the _Least Squares_ fit, which makes the _Maximum Likelihood_ and _Gradient Descent_ seem the optimal choice, whereas without it LS somehow seems to be the best choice, with ML the worst.

Which one is supposed to be the optimal technique?

**Comment by grd349** [comment]
I think I would say that least squares is the least likely to be optimal across all cases. 

Maximum likelihood really refers to a large number of methods (or at least the idea behind the method), for which gradient descent is one of these methods (and I guess there are a number of different gradient descent methods). 

We can discuss on Tuesday!  If you think about it in terms of Bayes then the likelihood is P(D | \theta) but then you need a way to find the maximum.  You'll also need a prior if you want to be semi Bayes.  You'll also want to estimate the posterior is you wan to be fully Bayes.
