### ISSUE TITLE
Converting datetime to decimal year

### ISSUE THREAD

**Issue by guner-aygin** [guner-aygin/Year-4-Project#4]
Is there a quick way of converting a datetime list to an array of decimal years (using astropy?). I am using new data & the GPR can't work with datetime format. 

https://github.com/guner-aygin/Year-4-Project/blob/0cca39b3a3ab24cdc1d2943534ed40aaaded97f7/Fitting_raw.ipynb

**Comment by grd349** [comment]
https://docs.astropy.org/en/stable/time/index.html

If you can read in the dates using astropy time then you can get the mjd back out which is time in units of days with some offset.
