### ISSUE TITLE
Std of GP samples

### ISSUE THREAD

**Issue by guner-aygin** [guner-aygin/Year-4-Project#5]
I am struggling to find a way of determining the std of the GP. 

I think the mean prediction is okay, but my attempt at getting the std returns only a single value, rather than a std for each point. How can I fix this? 

(See the bottom of https://github.com/guner-aygin/Year-4-Project/blob/main/Full%20Cycle%20Modelling/GP_SVG.ipynb)

**Comment by grd349** [comment]
Yeah - I guess you'll need to use the mean here. Just make sure you state
you are using the mean.

Make sense?

G
